In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn .preprocessing import StandardScaler
from sklearn.metrics import r2_score,mean_squared_error

In [50]:
df = pd.read_csv("Housing.csv")
df.shape

(545, 13)

In [51]:
df.head()
df.tail()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
540  1820000  3000         2          1        1      yes        no      yes   
541  1767150  2400         3          1        1       no        no       no   
542  1750000  3620         2          1        1      yes        no       no   
543  1750000  2910         3          1        1       no        no       no   
544  1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished

In [7]:
encoder = LabelEncoder()

In [8]:
en_mainroad = encoder.fit_transform(df.loc[:,['mainroad']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
en_guestroom = encoder.fit_transform(df.loc[:,['guestroom']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
en_basement = encoder.fit_transform(df.loc[:,['basement']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
en_hotwaterheating = encoder.fit_transform(df.loc[:,['hotwaterheating']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
en_airconditioning = encoder.fit_transform(df.loc[:,['airconditioning']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
en_prefarea = encoder.fit_transform(df.loc[:,['prefarea']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
en_furnishingstatus = encoder.fit_transform(df.loc[:,['furnishingstatus']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
df.loc[:,['en_mainroad']] = en_mainroad

In [16]:
df.loc[:,['en_guestroom']] = en_guestroom

In [17]:
df.loc[:,['en_basement']] = en_basement

In [18]:
df.loc[:,['en_hotwaterheating']] = en_hotwaterheating

In [19]:
df.loc[:,['en_airconditioning']] = en_airconditioning

In [20]:
df.loc[:,['en_prefarea']] = en_prefarea

In [21]:
df.loc[:,['en_furnishingstatus']] = en_furnishingstatus

In [22]:
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  \
0              no             yes        2      yes        furnished   
1              no             yes        3       no        furnished   
2              no              no        2      yes   semi-furnished   
3              no             yes        3      yes        furnished   
4              no             yes        2       no        furnished   

   en_mainroad  en_guestroom  en_basement  en_hotwaterheating  \
0            1             0            0                   0   
1            1             0            0                   0   
2            1             0            1                   0   
3            1             0            1                   0   
4            1             1            1                   0   

   en_airconditioning  en_prefarea  en_furnishingstatus  
0                   1            1                    0  
1                   1            0                    0  
2                   0            1                    1  
3                   1            1                    0  
4                   1            0                    0

In [23]:
df.loc[:,'en_guestroom'].value_counts()


en_guestroom
0    448
1     97
Name: count, dtype: int64

In [24]:
df.loc[:,'guestroom'].value_counts()

guestroom
no     448
yes     97
Name: count, dtype: int64

In [25]:
df.drop(['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea','furnishingstatus'], axis= 1,inplace=True)

In [26]:
df

price  area  bedrooms  bathrooms  stories  parking  en_mainroad  \
0    13300000  7420         4          2        3        2            1   
1    12250000  8960         4          4        4        3            1   
2    12250000  9960         3          2        2        2            1   
3    12215000  7500         4          2        2        3            1   
4    11410000  7420         4          1        2        2            1   
..        ...   ...       ...        ...      ...      ...          ...   
540   1820000  3000         2          1        1        2            1   
541   1767150  2400         3          1        1        0            0   
542   1750000  3620         2          1        1        0            1   
543   1750000  2910         3          1        1        0            0   
544   1750000  3850         3          1        2        0            1   

     en_guestroom  en_basement  en_hotwaterheating  en_airconditioning  \
0               0            0                   0                   1   
1               0            0                   0                   1   
2               0            1                   0                   0   
3               0            1                   0                   1   
4               1            1                   0                   1   
..            ...          ...                 ...                 ...   
540             0            1                   0                   0   
541             0            0                   0                   0   
542             0            0                   0                   0   
543             0            0                   0                   0   
544             0            0                   0                   0   

     en_prefarea  en_furnishingstatus  
0              1                    0  
1              0                    0  
2              1                    1  
3              1                    0  
4              0                    0  
..           ...                  ...  
540            0                    2  
541            0                    1  
542            0                    2  
543            0                    0  
544            0                    2  

[545 rows x 13 columns]

In [27]:
scalar = StandardScaler()

In [28]:
s_area = scalar.fit_transform(df.iloc[:,1:2])

In [29]:
df.insert(1,column='s_area',value=s_area)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   price                545 non-null    int64  
 1   s_area               545 non-null    float64
 2   area                 545 non-null    int64  
 3   bedrooms             545 non-null    int64  
 4   bathrooms            545 non-null    int64  
 5   stories              545 non-null    int64  
 6   parking              545 non-null    int64  
 7   en_mainroad          545 non-null    int32  
 8   en_guestroom         545 non-null    int32  
 9   en_basement          545 non-null    int32  
 10  en_hotwaterheating   545 non-null    int32  
 11  en_airconditioning   545 non-null    int32  
 12  en_prefarea          545 non-null    int32  
 13  en_furnishingstatus  545 non-null    int32  
dtypes: float64(1), int32(7), int64(6)
memory usage: 44.8 KB


In [31]:
# x,y = df.iloc[:,2:],df.iloc[:,1:2]

In [32]:
x,y = df.iloc[:,2:],df.iloc[:,0:1]

In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=50)

In [34]:
y

price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [35]:
x_test

area  bedrooms  bathrooms  stories  parking  en_mainroad  en_guestroom  \
333  3000         3          1        2        0            1             0   
37   9000         4          2        4        2            1             0   
396  3640         2          1        1        1            1             0   
494  6800         2          1        1        0            1             0   
536  3420         5          1        2        0            0             0   
..    ...       ...        ...      ...      ...          ...           ...   
269  3900         3          1        2        0            1             0   
472  3630         4          1        2        3            1             0   
521  3635         2          1        1        0            0             0   
145  5000         3          1        4        0            1             0   
244  5320         3          1        2        0            1             1   

     en_basement  en_hotwaterheating  en_airconditioning  en_prefarea  \
333            0                   0                   0            0   
37             0                   0                   1            0   
396            0                   0                   0            0   
494            0                   0                   0            0   
536            0                   0                   0            0   
..           ...                 ...                 ...          ...   
269            0                   0                   0            0   
472            0                   0                   0            0   
521            0                   0                   0            0   
145            0                   0                   0            0   
244            1                   0                   0            1   

     en_furnishingstatus  
333                    1  
37                     0  
396                    1  
494                    2  
536                    2  
..                   ...  
269                    2  
472                    1  
521                    2  
145                    0  
244                    1  

[109 rows x 12 columns]

In [36]:
model = LinearRegression()

In [37]:
model.fit(x_train,y_train)

LinearRegression()

In [38]:
y_pred = model.predict(x_test)


In [39]:
y_test

price
333  3920000
37   7980000
396  3500000
494  2730000
536  1960000
..       ...
269  4375000
472  3010000
521  2408000
145  5600000
244  4550000

[109 rows x 1 columns]

In [40]:
y_pred


array([[ 3358068.53544935],
       [ 8464191.99499452],
       [ 3205429.62578452],
       [ 3436225.70027218],
       [ 2972459.97655173],
       [ 7375555.83990435],
       [ 6426149.39050664],
       [ 4460869.40645302],
       [ 3845075.6553084 ],
       [ 4542704.51165384],
       [ 2479695.2655871 ],
       [ 4012051.85203732],
       [ 3728004.14128508],
       [ 5191969.36010061],
       [ 3851534.17868486],
       [ 3634498.49587972],
       [ 4891753.13599567],
       [ 4017390.97506914],
       [ 6255633.83606134],
       [ 6596313.36949275],
       [ 5220009.43966466],
       [ 6257876.38468613],
       [ 4403616.1605166 ],
       [ 3518943.92736549],
       [ 4996035.11953328],
       [ 2693941.34633538],
       [ 4890504.42832327],
       [ 3093629.39198836],
       [ 5843345.10526967],
       [ 2876011.09352742],
       [ 3954949.01527097],
       [ 4504875.19900095],
       [ 3923068.04639501],
       [ 5160019.1352634 ],
       [ 6328907.80195805],
       [ 2715873.820

In [41]:
r2_score(y_test,y_pred)

0.7624579467323477

In [42]:
mean_squared_error(y_test,y_pred)

807848838640.2025

In [43]:
import joblib

In [44]:
joblib.dump(model,'HousePrice_pridiction.pkl')

['HousePrice_pridiction.pkl']

In [45]:
m = joblib.load('HousePrice_pridiction.pkl')

In [46]:
import numpy as np
a = np.array([1.777,2,1,2,0,1,1,0,1,0,0,0])
a

array([1.777, 2.   , 1.   , 2.   , 0.   , 1.   , 1.   , 0.   , 1.   ,
       0.   , 0.   , 0.   ])

In [47]:
m.predict([a])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[3861139.43820334]])

In [48]:
model.predict([a])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[3861139.43820334]])